=== mmoonly/task02/src/main/resources/db.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.epam.task.com/appliance"
           xmlns:tns="http://www.epam.task.com/appliance">
    <xs:element name="appliances">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="oven" type="tns:ovenAppliance" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="laptop" type="tns:laptopAppliance" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="refrigerator" type="tns:refrigeratorAppliance" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="vacuum-cleaner" type="tns:vacuumCleanerAppliance" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="tablet-PC" type="tns:tabletPCAppliance" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="speakers" type="tns:speakersAppliance" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ovenAppliance">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="weight" type="xs:double"/>
            <xs:element name="capacity" type="xs:double"/>
            <xs:element name="depth" type="xs:double"/>
            <xs:element name="height" type="xs:double"/>
            <xs:element name="width" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="laptopAppliance">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="os" type="tns:os"/>
            <xs:element name="battery-capacity" type="xs:double"/>
            <xs:element name="memory-rom" type="xs:double"/>
            <xs:element name="system-memory" type="xs:double"/>
            <xs:element name="cpu" type="tns:cpu"/>
            <xs:element name="display-size" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="refrigeratorAppliance">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="weight" type="xs:double"/>
            <xs:element name="freezer-capacity" type="xs:double"/>
            <xs:element name="overall-capacity" type="xs:double"/>
            <xs:element name="height" type="xs:double"/>
            <xs:element name="width" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vacuumCleanerAppliance">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="filter-type" type="tns:filter-type"/>
            <xs:element name="bag-type" type="tns:bag-type"/>
            <xs:element name="wand-type" type="tns:wand-type"/>
            <xs:element name="motor-speed-regulation" type="xs:double"/>
            <xs:element name="cleaning-width" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tabletPCAppliance">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="color" type="tns:color"/>
            <xs:element name="battery-capacity" type="xs:double"/>
            <xs:element name="memory-rom" type="xs:double"/>
            <xs:element name="flash-memory-capacity" type="xs:double"/>
            <xs:element name="display-size" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="speakersAppliance">
        <xs:sequence>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="power-consumption" type="xs:double"/>
            <xs:element name="number-of-speakers" type="xs:double"/>
            <xs:element name="cord-length" type="xs:double"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="os">
        <xs:restriction base="xs:string">
            <xs:enumeration value="WINDOWS"/>
            <xs:enumeration value="LINUX"/>
            <xs:enumeration value="MACOS"/>
            <xs:enumeration value="ANDROID"/>
            <xs:enumeration value="IOS"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cpu">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INTEL_CORE_I3"/>
            <xs:enumeration value="INTEL_CORE_I5"/>
            <xs:enumeration value="INTEL_CORE_I7"/>
            <xs:enumeration value="INTEL_CORE_I9"/>
            <xs:enumeration value="AMD_RYZEN_5"/>
            <xs:enumeration value="AMD_RYZEN_9"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="filter-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="C"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="bag-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="B2"/>
            <xs:enumeration value="C3"/>
            <xs:enumeration value="D4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="wand-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ALL_IN_ONE"/>
            <xs:enumeration value="LONG"/>
            <xs:enumeration value="SHORT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="color">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BLUE"/>
            <xs:enumeration value="YELLOW"/>
            <xs:enumeration value="RED"/>
            <xs:enumeration value="GREEN"/>
            <xs:enumeration value="GRAY"/>
            <xs:enumeration value="BLACK"/>
            <xs:enumeration value="WHITE"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== mmoonly/task02/src/main/resources/db.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<tc:appliances xmlns:tc="http://www.epam.task.com/appliance"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.epam.task.com/appliance db.xsd">

    <oven>
        <price>100.0</price>
        <power-consumption>1900.0</power-consumption>
        <weight>9.3</weight>
        <capacity>27.0</capacity>
        <depth>55.0</depth>
        <height>47.5</height>
        <width>39.0</width>
    </oven>
    <oven>
        <price>350.0</price>
        <power-consumption>1950.0</power-consumption>
        <weight>12.5</weight>
        <capacity>26.9</capacity>
        <depth>89.0</depth>
        <height>91.7</height>
        <width>20.1</width>
    </oven>

    <laptop>
        <price>1150.0</price>
        <os>WINDOWS</os>
        <battery-capacity>170.1</battery-capacity>
        <memory-rom>3400.0</memory-rom>
        <system-memory>3351.0</system-memory>
        <cpu>INTEL_CORE_I3</cpu>
        <display-size>15.5</display-size>
    </laptop>
    <laptop>
        <price>7850.0</price>
        <os>ANDROID</os>
        <battery-capacity>2230.0</battery-capacity>
        <memory-rom>11300.0</memory-rom>
        <system-memory>3281.0</system-memory>
        <cpu>INTEL_CORE_I5</cpu>
        <display-size>13.6</display-size>
    </laptop>

    <refrigerator>
        <price>9000.0</price>
        <power-consumption>1234.0</power-consumption>
        <weight>90.4</weight>
        <freezer-capacity>87.0</freezer-capacity>
        <overall-capacity>900.0</overall-capacity>
        <height>76.0</height>
        <width>65.0</width>
    </refrigerator>
    <refrigerator>
        <price>3680.0</price>
        <power-consumption>178.2</power-consumption>
        <weight>39.0</weight>
        <freezer-capacity>98.0</freezer-capacity>
        <overall-capacity>401.0</overall-capacity>
        <height>280.0</height>
        <width>80.0</width>
    </refrigerator>

    <vacuum-cleaner>
        <price>1983.0</price>
        <power-consumption>653.0</power-consumption>
        <filter-type>C</filter-type>
        <bag-type>B2</bag-type>
        <wand-type>SHORT</wand-type>
        <motor-speed-regulation>5600.0</motor-speed-regulation>
        <cleaning-width>35.0</cleaning-width>
    </vacuum-cleaner>
    <vacuum-cleaner>
        <price>8920.0</price>
        <power-consumption>320.0</power-consumption>
        <filter-type>A</filter-type>
        <bag-type>B2</bag-type>
        <wand-type>ALL_IN_ONE</wand-type>
        <motor-speed-regulation>6530.0</motor-speed-regulation>
        <cleaning-width>71.0</cleaning-width>
    </vacuum-cleaner>

    <tablet-PC>
        <price>8200.0</price>
        <color>YELLOW</color>
        <battery-capacity>340.0</battery-capacity>
        <memory-rom>16000.0</memory-rom>
        <flash-memory-capacity>3.3</flash-memory-capacity>
        <display-size>16.2</display-size>
    </tablet-PC>
    <tablet-PC>
        <price>5230.0</price>
        <color>GRAY</color>
        <battery-capacity>321.0</battery-capacity>
        <memory-rom>2340.0</memory-rom>
        <flash-memory-capacity>6.1</flash-memory-capacity>
        <display-size>16.6</display-size>
    </tablet-PC>

    <speakers>
        <price>290.5</price>
        <power-consumption>11.1</power-consumption>
        <number-of-speakers>6.0</number-of-speakers>
        <cord-length>2.0</cord-length>
    </speakers>
    <speakers>
        <price>531.0</price>
        <power-consumption>19.0</power-consumption>
        <number-of-speakers>2.0</number-of-speakers>
        <cord-length>8.2</cord-length>
    </speakers>
    <speakers>
        <price>521.0</price>
        <power-consumption>13.2</power-consumption>
        <number-of-speakers>7.0</number-of-speakers>
        <cord-length>6.2</cord-length>
    </speakers>

</tc:appliances>
